### PR TITLE
Add python3 support

### PR DESCRIPTION
**Pull request by sijis**
These changes add python3 support and fix the tests.

### CODE REVIEW

**Comment by sijis** [comment]
Any feedback on this?

**Comment by tedops** [comment]
I still see some lines (like print()) that don't have parentheses. Is this PR going for a full conversion of Party to Python3?

**Comment by sijis** [comment]
The change will allow the library to run in python2 and python3. It mainly revolves around urllib encode and how that library path changed between [python] versions.

I'm not seeing any `print` statements in `party.py`. Are you are referring to the `lookup.py` in `examples` directory? I see one there. I can update that example.

**Comment by tedops** [comment]
Ah yes, I was looking at `lookup.py`. No update necessary. Thanks for making this Python3 compatible!

**Pull request merged**
